### ISSUE TITLE
Не выходит привязать ползунок Tkinter к переменной Index, обозначающей масштаб графика.

### ISSUE THREAD

**Issue by Antohnio123** [aanikin/Python#6]
Добавил drawGraphic.py, рисующий графики.   
Формулу вводим с переменной x, она переводится в eval и рисуется. При вводе формулы главное не забывать ставить знак умножения.
Экран очищается кнопкой Clear Screen.
Есть переменная Index, которая регулирует масштаб графика, из кода она успешно меняется и графики строятся в разных масштабах.  Но никак не получается привязать к ней def Scale( ), который вызывается кнопкой у ползунка Scale и выбранный на ползунке масштаб применяет...    
def Scale ( ) тупо не хочет видеть глобальную переменную Index и влиять на неё.  Что я упустил?

**Comment by aanikin** [comment]
попробовать не использовать глобальные переменные... это скорее ошибка дизайна, и для использования глобальных переменных есть специальные слова global и non local

**Comment by Antohnio123** [comment]
Точно, спасибо.
Нашёл тему на StackOverflow про использование глобальных переменных в функциях Python: https://ru.stackoverflow.com/questions/358/Глобальные-переменные-в-python-сохранить-локальную-переменную-от-вызова-к-вызов?newreg=e3c007a4b19e489b81ac830468b1b0af
Их там, оказывается, ещё и объявлять нужно внутри функции перед использованием.

**Comment by aanikin** [comment]
Сегодня на лекции это будет. Но полезно чуть забегать вперед и понимать зачем это.
